name: Develop Environment Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code changes
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"

      - name: Pull changes and restart project on server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.server_user }}@${{ secrets.server_ip }} \
          "cd ~/book_project/front && 
          git pull && docker compose down front && 
          docker compose up -d --build --remove-orphans"